## Create a data set

In [1]:
import pandas as pd

In [2]:
data = {
    'Area': [1000, 1500, 2000, 2500, 3000],
    'Bedrooms': [2, 3, 4, 4, 5],
    'Bathrooms': [1, 2, 3, 3, 4],
    'Price': [3000000, 4500000, 6000000, 7500000, 9000000]
}

In [5]:
df = pd.DataFrame(data)
df

   Area  Bedrooms  Bathrooms    Price
0  1000         2          1  3000000
1  1500         3          2  4500000
2  2000         4          3  6000000
3  2500         4          3  7500000
4  3000         5          4  9000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Area       5 non-null      int64
 1   Bedrooms   5 non-null      int64
 2   Bathrooms  5 non-null      int64
 3   Price      5 non-null      int64
dtypes: int64(4)
memory usage: 292.0 bytes

In [7]:
df.describe()

              Area  Bedrooms  Bathrooms         Price
count     5.000000  5.000000   5.000000  5.000000e+00
mean   2000.000000  3.600000   2.600000  6.000000e+06
std     790.569415  1.140175   1.140175  2.371708e+06
min    1000.000000  2.000000   1.000000  3.000000e+06
25%    1500.000000  3.000000   2.000000  4.500000e+06
50%    2000.000000  4.000000   3.000000  6.000000e+06
75%    2500.000000  4.000000   3.000000  7.500000e+06
max    3000.000000  5.000000   4.000000  9.000000e+06

## Seprate feature and target

In [13]:
x = df.drop(columns= "Price")
y = df[["Price"]]

## Step 3: Train Mosel

In [19]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x,y)

LinearRegression()

## Step 4: Predict New House Price

In [20]:
predict = model.predict([[2000,4,3]])
print(predict)

[[6000000.]]

D:\anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

## Step 5: Check Model Score

In [21]:
print(model.score(x,y))

1.0